### ISSUE TITLE
serialize and error[E0642]

### ISSUE THREAD

**Issue by wahn** [ProgrammingRust/mandelbrot#2]
Having problems to compile:

```shell
$ cargo clean
$ rustup -V
rustup 1.10.0 (c6a8f7c60 2018-01-25)
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
$ cargo check
$ cargo check
   Compiling rustc-serialize v0.3.19
   Compiling deque v0.3.1
   Compiling num-iter v0.1.32
   Compiling miniz-sys v0.1.7
error[E0642]: patterns aren't allowed in methods without bodies
   --> /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^

   Compiling rayon v0.4.0
   Compiling flate2 v0.2.14
   Compiling jpeg-decoder v0.1.6
   Compiling png v0.5.2
error: aborting due to previous error

error: Could not compile `rustc-serialize`.

To learn more, run the command again with --verbose.
```

P.S.: Thanks for the [Programming Rust](http://shop.oreilly.com/product/0636920040385.do) **book**. I'm really enjoying it so far ...

**Comment by jimblandy** [comment]
I'm glad you're enjoying the book. Thanks very much for taking the time to submit this bug report.

It seems like the `Cargo.lock` in this repo is selecting a very old version of rustc_serialize, which contains code that was [turned into a compilation error][e] quite a while ago. If you run `cargo update` and try building again, you should get a newer version, and the build should work.

I'll update the `Cargo.lock` file in this repo.

[e]: https://github.com/rust-lang/rust/issues/35203

**Comment by jimblandy** [comment]
Okay, I think I've updated `Cargo.lock` appropriately on all the branches. Please give this a try and re-open this issue if it doesn't work for you.

**Comment by wahn** [comment]
Thanks, `cargo update` did resolve the issue, as you said.

**Comment by fdg-org** [comment]
FYI, in [Branch `task-queue`](https://github.com/ProgrammingRust/mandelbrot/tree/task-queue) `Cargo.lock` is not updated correctly.

**Comment by jimblandy** [comment]
Thanks for reporting this. I think that one is updated now. If not, please re-open.
