### ISSUE TITLE
The naming of the arguments is confusing

### ISSUE THREAD

**Issue by ianchanning** [ProgrammingRust/mandelbrot#5]
You specify the arguments as:

`Usage: mandelbrot FILE PIXELS UPPERLEFT LOWERRIGHT`

But what it actually is, is the corner values are inverted from how they are described:

`Usage: mandelbrot FILE PIXELS <LEFT,TOP> <RIGHT,BOTTOM>`

Even easier to understand is to use common CSS terminology and split them out:

`Usage: mandelbrot FILE PIXELS TOP RIGHT BOTTOM LEFT` - but that would obviously require a code change.

**Comment by jimblandy** [comment]
Thank you for this bug report! I can never tell how closely readers actually follow along with the book, so it's in one sense reassuring that people are reading so carefully.

I think you're right about `<LEFT,TOP> <RIGHT,BOTTOM>`. I'll make this change in future printings.

Now, following CSS's lead would certainly be something familiar to many developers. But that would leave `parse_pair` with only one use (parsing `PIXELS`), which would make it less clear why it's useful as a generic function. So, I think in this particular case pedagogy trumps CSS familiarity. (Also, we'd want to default missing values the way CSS does... which would be interesting, but it's not quite what we need at this point in the tutorial.)

**Comment by jimblandy** [comment]
Okay, this has been changed.

**Comment by ianchanning** [comment]
Thank you for looking into this, yes I quite understand what you mean. It's primary idea is to give good examples of useful code. Thank you again for this excellent code. My colleagues loved the craziness of doing a fractal generator as an intro to Rust programming.
