### ISSUE TITLE
Doesn't compile with rust 1.53.0

### ISSUE THREAD

**Issue by richsalz** [ProgrammingRust/mandelbrot#7]
Thoughts or work-arounds?

**Comment by richsalz** [comment]
never mind, didn't have the dependencies right.  (Maybe say that upfront for those typing in the code as you explain it :)

**Comment by jimblandy** [comment]
Thanks for writing. Which dependencies were you missing?

**Comment by richsalz** [comment]
It was all in the Cargo file, which appeared after the source code :)

**Comment by jimblandy** [comment]
I'll see about reordering that. Probably the other examples are similar. Thank you!

**Comment by richsalz** [comment]
Glad to help.  Am really enjoying the book!
